// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_xnCSuugUqAtfmFKGKUkuZN9k4fY72pw',
    appId: '1:717417408352:web:64fd04af9e9e3fa4236005',
    messagingSenderId: '717417408352',
    projectId: 'flutter-crud-39d07',
    authDomain: 'flutter-crud-39d07.firebaseapp.com',
    storageBucket: 'flutter-crud-39d07.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5bxaHz14SRXr-fR1cuB0kEFLUXVTtPo0',
    appId: '1:717417408352:android:7ccbbbf0da47a69a236005',
    messagingSenderId: '717417408352',
    projectId: 'flutter-crud-39d07',
    storageBucket: 'flutter-crud-39d07.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOX8n8IwEOZyEfI8cXfjyzBMffEOtvhc8',
    appId: '1:717417408352:ios:df8778e8879f0c4e236005',
    messagingSenderId: '717417408352',
    projectId: 'flutter-crud-39d07',
    storageBucket: 'flutter-crud-39d07.appspot.com',
    iosClientId: '717417408352-1coujemmjgif3nmohooiak8j103sl1hf.apps.googleusercontent.com',
    iosBundleId: 'com.example.codingFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOX8n8IwEOZyEfI8cXfjyzBMffEOtvhc8',
    appId: '1:717417408352:ios:df8778e8879f0c4e236005',
    messagingSenderId: '717417408352',
    projectId: 'flutter-crud-39d07',
    storageBucket: 'flutter-crud-39d07.appspot.com',
    iosClientId: '717417408352-1coujemmjgif3nmohooiak8j103sl1hf.apps.googleusercontent.com',
    iosBundleId: 'com.example.codingFlutter',
  );
}
